<?php

define('QODE_WOOCOMMERCE_CHECKOUT_INTEGRATION', '2.0.2');
define('QODE_WOOCOMMERCE_CHECKOUT_INTEGRATION_PATH', dirname(__FILE__));
define('QODE_WOOCOMMERCE_CHECKOUT_INTEGRATION_REL_PATH', dirname(plugin_basename(__FILE__ )));
define('QODE_WOOCOMMERCE_CHECKOUT_INTEGRATION_URL_PATH', plugin_dir_url( __FILE__ ));